const path = require('path')
const m1 = path.basename('Z:\\Programming\\CSE-Sem6\\Advanced Web Technologies\\Practical 2\\file.txt')
const m2 = path.dirname('Z:\\Programming\\CSE-Sem6\\Advanced Web Technologies\\Practical 2\\file.txt')
console.log(m1)
console.log(m2)
const m3 = path.extname(__filename)
console.log(m3)